scss_files: '_sass/**/*.scss'

exclude:
  - '_sass/vendor/*'
  - '_sass/partials/_reset.scss'

linters:
  ElsePlacement:
    enabled: true
    style: new_line

  HexLength:
    enabled: true
    style: long

  HexNotation:
    style: uppercase

  Indentation:
    severity: warning
    width: 4

  LeadingZero:
    style: include_zero

  NameFormat:
    enabled: false

  SelectorFormat:
    enabled: false
    convention: ^\.(_)?[a-z]+-[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$

  SingleLinePerSelector:
    allow_single_line_rule_sets: true
