# Stakx configuration

collections:
  - name: posts
    folder: _posts
  - name: experience
    folder: _experience
  - name: accomplishments
    folder: _accomplishments

data:
  - _data

exclude:
  - README.md
  - feed.xml
  - stakx

pageviews:
  - _pages

theme: basics
debug: true

# Site Configuration
title: allejo.io | A developer pretending to know what he's doing
