# Site settings
title: allejo
description: >
  A Jekyll blog about an arrogant, sarcastic, and self-centered college student
  who thinks he's funny. He gets bored, a lot.
baseurl: ""
url: "https://allejo.io"

# Build settings
markdown: redcarpet

keep_files:
  - '_site/css'

exclude:
  - README.md
  - node_module
  - css
  - _sass
