# Site settings
title: allejo
description: >
  A Jekyll blog about an arrogant, sarcastic, and self-centered college student
  who thinks he's funny. He gets bored, a lot.
baseurl: ""
url: "https://allejo.io"

# Build settings
markdown: redcarpet

gems:
  - jekyll-gist

sass:
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
