# Site settings
title: allejo
description: >
  A Jekyll blog about an arrogant, sarcastic, and self-centered colleged student
  who sometimes is funny. He also gets bored a lot.
baseurl: ""
url: "https://allejo.io"
twitter_username: allejome
github_username:  allejo

# Build settings
markdown: redcarpet

exclude:
  - README.md
  - allejo.sublime-project
