# Site settings
title: allejo
baseurl: ""
url: "https://allejo.io"

# Build settings
markdown: redcarpet

gems:
  - jekyll-gist

sass:
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
