# Site settings
title: allejo
baseurl: ""
url: "https://allejo.io"

collections:
  - experience

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:title/
      banner: coast
  - scope:
      path: ""
      type: experience
    values:
      layout: experience-block

# Build settings
markdown: redcarpet

gems:
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
