# Stakx configuration

collections:
  - name: posts
    folder: _posts
  - name: accomplishments
    folder: _about/accomplishments
  - name: communities
    folder: _about/communities
  - name: experience
    folder: _about/experience
  - name: projects
    folder: _projects

data:
  - _data

exclude:
  - README.md
  - feed.xml
  - stakx
  - yarn.lock
  - bower_components/
  - Gulpfile.js
  - Makefile
  - bower.json
  - bower-shrinkwrap.json
  - package.json
  - .idea/

pageviews:
  - _pages

templates:
  redirect: _layouts/redirect.html.twig

# Site Configuration
title: allejo.io
motto: interstellar space pirate extraordinaire
url: https://allejo.io

author:
  name: Vladimir Jimenez
  email: me@allejo.io

social:
  opengraph:
    image: assets/images/open-graph.jpg
  twitter:
    username: allejome
  kofi:
    username: allejo
  coffee:
    username: allejo
  paypal:
    username: allejo

api:
  wufoo: "AES6LivHXygHJs7HoWzs5P4VV3fZYvKQvUmhXp9li0s="
